name: daily-archive

on:
  schedule:
    # 01:00 UTC minden nap -> Berlin idő szerint ez jellemzően 02:00 vagy 03:00
    - cron: '0 1 * * *'
  workflow_dispatch: {}  # lehet kézzel is futtatni a GitHub UI-ból

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp internetarchive

      - name: Run backup
        env:
          IA_ACCESS_KEY_ID: ${{ secrets.IA_ACCESS_KEY_ID }}
          IA_SECRET_ACCESS_KEY: ${{ secrets.IA_SECRET_ACCESS_KEY }}
        run: |
          python backup.py
